twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        formato_fecha: '%app.formato_fecha%'
        # se pone aca por que va para el menu superior y así no hace falta pasarlo en cada controlador
        categoria_repository: '@App\Repository\CategoriaRepository'
        servicio_mio: '@App\Service\ServicioMio'
        generador_de_mensajes: '@App\Service\MessageGenerator'

when@test:
    twig:
        strict_variables: true
